name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Checkout wiki
      uses: actions/checkout@v3
      with:
        repository: ${{github.repository}}.wiki
        path: ./.github/wiki/

    - name: Generate coverage report
      shell: bash
      run: |
        ./coverage.sh
        mv ./coverage.svg ./.github/wiki/
        mv ./coverage.html ./.github/wiki/
        cat ./coverage.log >> ./.github/wiki/coverage.log
        sort -u -o ./.github/wiki/coverage.log ./.github/wiki/coverage.log

    - name: Push to wiki
      shell: bash
      run: |
        cd ./.github/wiki/
        git config --local user.name "GitHub Action"
        git config --local user.email "action@github.com"
        git add coverage.svg coverage.log coverage.html
        git diff-index --quiet HEAD || git commit -m "Update coverage" && git push
